# Generated by Django 4.0.3 on 2022-04-14 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_num',
            field=models.IntegerField(default=0, verbose_name='フォロワー'),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following_num',
            field=models.IntegerField(default=0, verbose_name='フォロー中'),
        ),
    ]
