# Generated by Django 4.0.3 on 2022-04-13 01:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='posted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 13, 1, 37, 24, 436760, tzinfo=utc)),
        ),
    ]
