# Generated by Django 4.0.3 on 2022-04-13 01:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_articlemodel_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='posted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 13, 1, 44, 13, 687089, tzinfo=utc)),
        ),
    ]
